---
abstract: 'check for spelling errors in code comments'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Cwd: '0'
  File::Basename: '0'
  File::Spec: '0'
  Test::Builder::Tester: '0'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::More: '0.88'
  Test::TempDir::Tiny: '0'
  constant: '0'
  lib: '0'
  perl: '5.006'
  subs: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Spelling-Comment
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  Carp: '0'
  Comment::Spell::Check: '0'
  Moo: '0'
  Pod::Wordlist: '0'
  Scalar::Util: '0'
  Test::Builder: '0'
  Test::XTFiles: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Test-Spelling-Comment/issues
  homepage: https://github.com/skirmess/Test-Spelling-Comment
  repository: https://github.com/skirmess/Test-Spelling-Comment.git
version: '0.005'
x_spdx_expression: BSD-2-Clause-FreeBSD
